name: Reject Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  reject_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check Pull Request User and Email
        run: |
          if [[ !"${{ github.event.pull_request.user.login }}" == "${{ secrets.PR_ALLOWED_USERNAME }}" || \
                !"${{ github.event.pull_request.user.email }}" == "${{ secrets.PR_ALLOWED_EMAIL }}" ]]; then
            echo "Rejecting pull request by specific user with specific email"
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"state": "closed"}' \
              "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
